"""
Generated by CHARMM-GUI (http://www.charmm-gui.org)

omm_barostat.py

This module is for pressure coupling methods in OpenMM.

Correspondance: jul316@lehigh.edu or wonpil@lehigh.edu
Last update: July 22, 2015
"""

from simtk.unit import *
from simtk.openmm import *
from simtk.openmm.app import *

def barostat(system, temp, p_ref, p_type, p_scale, p_XYMode, p_ZMode, p_tens, p_freq):

    if p_type == 'isotropic':
        barostat = MonteCarloBarostat( p_ref*bar, temp*kelvin )
    if p_type == 'membrane':
        p_tens = p_tens*10.0
        barostat = MonteCarloMembraneBarostat( p_ref*bar, p_tens*bar*nanometers, temp*kelvin, p_XYMode, p_ZMode, p_freq )
    if p_type == 'anisotropic':
        barostat = MonteCarloAnisotropicBarostat( p_ref*bar, temp*kelvin, p_scale[0], p_scale[1], p_scale[2], p_freq )

    system.addForce(barostat)

    return system
